apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: es-db-credentials
spec:
  refreshInterval: "10s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: db-credentials
    template:
      engineVersion: v2
      data: 
        credentials: |
          db_con="{{ .db_host }}"
          db_user="{{ .db_username }}"
          db_password="{{ .db_password }}"
        
  data:
  - secretKey: db_host
    remoteRef:
      key: gitops-demo-credentials
      property: host
  - secretKey: db_username
    remoteRef:
      key: gitops-demo-credentials
      property: username
  - secretKey: db_password
    remoteRef:
      key: gitops-demo-credentials
      property: password
    
